<a href="<?php echo $this->url(array('action'=>'overview')); ?>">&lt; Back to site overview</a>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
	var graphData = <?php echo json_encode($this->graphData); ?>;
</script>
<div id="chart"></div>

<div class="uniForm">
	<div class="buttonHolder">
		<input type="button" value="Previous investigation" class="secondaryAction prev">
		<input type="button" value="Next investigation" class="primaryAction next">
	</div>
</div>

<!--<p>Investigation Max Depth:	--><?php //print $this->maxDepth; ?><!--</p>-->
<!--<p>Investigation Min Depth: --><?php //print $this->minDepth; ?><!--</p>-->
<!--<p>Investigation Max Width:	--><?php //print $this->maxWaterWidth; ?><!--</p>-->
<!--<p>Investigation Min Width: --><?php //print $this->minWaterWidth; ?><!--</p>-->


	<div clas='siteInvestigationInfo'>
		<table>
			<thead>
				<th>Measurement</th><th>Value</th>
			</thead>
			<tbody>
				<tr><td>Mean Flow:</td><td><?php print round($this->meanFlowrate, 2); ?> m/s</td></tr>
				<tr><td>Mean Depth:</td><td><?php print round($this->meanDepth, 2); ?> m</td></tr>
			</tbody>
		</table>
	</div>