INSERT into investigation (startDate, schoolName) VALUES ('2010-11-23','Guildford');
INSERT into sites (lat, lon, title, centre) VALUES ('0.107686', '0.291824', 'Harbourne', 'Slapton');
INSERT into siteinvestigations (siteId, investigationId) values ('1','1');

INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Distance Downstream','','0');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Water Width','','0.6');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Wetted perimeter','','0.76');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Gradient','','0.09');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Depth left','','0.04');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Depth centre left','','0.07');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Depth centre','','0.14');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Depth centre right','','18');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Depth right','','0.16');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Left Flowrate','','0');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Centre Flowrate','','0.215');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Right Flowrate','','0.424');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Bedload length','1','4.4');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Bedload length','2','2.4');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Bedload length','3','8.5');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Bedload length','4','3.3');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Bedload length','5','15.2');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Bedload length','6','5.8');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Bedload length','7','10.6');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Bedload length','8','5.7');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Bedload length','9','10.7');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Bedload length','10','2.1');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Very Angular','','1');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Angular','','4');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Sub Angular','','4');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Sub Rounded','','1');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Rounded','','0');
INSERT INTO measurements (siteInvestigationID, type, investigationSeriesIndex, value) VALUES ('1','Well rounded','','0');