<form method="post" action="<?php echo $this->url(); ?>" enctype="multipart/form-data">
	<input type="file" name="file" />
	<input type="submit" value="Upload" />
</form>

<?php print_r($this->investigation); ?>
<?php die(); ?>

<?php if ($this->sites) : ?>
<ul>
	<?php foreach ($this->sites as $site) : ?>
	<li>
		<?php echo $site->name; ?>
		<ul>
			<?php foreach ($site->data as $type=>$values) : ?>
			<li>
				<?php echo $type; ?>: <?php echo implode(', ', $values); ?>
			</li>
			<?php endforeach; ?>
		</ul>
	</li>
	<?php endforeach; ?>
</ul>
<?php endif; ?>
