<form method="post" action="<?php echo $this->url(); ?>" enctype="multipart/form-data" class="uniForm">
	<fieldset class="inlineLabels">
		<legend>Upload spreadsheet</legend>
		<div class="ctrlHolder">
			<label for="file">File</label>
			<input type="file" name="file" id="file" />
		</div>
		<div class="buttonHolder">
			<input type="submit" value="Upload" class="primaryAction" />
		</div>
	</fieldset>
</form>