<form method="post" action="<?php echo $this->url(); ?>" enctype="multipart/form-data" class="uniForm">
	<fieldset class="inlineLabels">
		<legend>Upload spreadsheet</legend>
		<div class="ctrlHolder">
			<label for="file">File</label>
			<input type="file" name="file" id="file" />
		</div>
		<div class="buttonHolder">
			<input type="submit" value="Upload" class="primaryAction" />
		</div>
	</fieldset>
</form>

<?php if ($this->sites) : ?>
<ul>
	<?php foreach ($this->sites as $site) : ?>
	<li>
		<?php echo $site->name; ?>
		<ul>
			<?php foreach ($site->data as $type=>$values) : ?>
			<li>
				<?php echo $type; ?>: <?php echo implode(', ', $values); ?>
			</li>
			<?php endforeach; ?>
		</ul>
	</li>
	<?php endforeach; ?>
</ul>
<?php endif; ?>
