<form method="post" action="<?php echo $this->url(array('action'=>'import')); ?>" class="uniForm">
	<fieldset class="inlineLabels">
		<legend><?php echo substr($this->uploadedFile, strrpos($this->uploadedFile, DIRECTORY_SEPARATOR)+1); ?></legend>
		<input type="hidden" name="phase" value="sheets" />
		<div class="ctrlHolder">
			<label for="date">Date</label>
			<input type="text" id="date" name="date" placeholder="e.g. 01-01-2012" value="<?php echo $this->date; ?>" />
		</div>
		<div class="ctrlHolder">
			<label for="school">School</label>
			<input type="text" id="school" name="school" value="<?php echo $this->school; ?>"/>
		</div>
		<div class="ctrlHolder">
			<label for="centre">Centre</label>
			<input type="text" id="centre" name="centre" value="<?php echo $this->centre; ?>"/>
		</div>
		<div class="ctrlHolder">
			<p class="label">Sheets to import</p>
			<ul class="blockLabels">
				<?php foreach ($this->sheets as $i=>$sheet) : ?>
				<li>
					<input id="sheet_<?php echo $i; ?>" name="sheets[]" type="checkbox" value="<?php echo $i; ?>" <?php if (in_array($i, $this->selectedSheets)) echo 'checked'; ?> />
					<label for="sheet_<?php echo $i; ?>"><?php echo $sheet['name']; ?></label>
				</li>
				<?php endforeach; ?>
			</ul>
		</div>
		<div class="buttonHolder">
			<input type="submit" value="Continue" class="primaryAction" />
		</div>
	</fieldset>
</form>
