<a href="<?php echo $this->url(array('action'=>'overview')); ?>">&lt; Back to investigation overview</a>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
	var graphData = <?php echo json_encode($this->graphData); ?>;
</script>
<div id="chart"></div>

<div class="uniForm">
	<div class="buttonHolder">
		<input type="button" value="Previous site" class="secondaryAction prev">
		<input type="button" value="Next site" class="primaryAction next">
	</div>
</div>
